update

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,34 +1,84 @@
 #!/usr/bin/env bash
-#install nginx on your web-01 server with the following configurations:
-#+      Listens on port 80
-#+      Returns the page containing "hello world" when queried at the root
-# Configure /redirect_me as a "301 moved permanently"
-# Include a custom 404 page containiing "Ceci n'est pas une page"
-# Include a custom HTTP response header named X-served-By That will show the
-# the name of the server
-apt-get -y update
-apt-get -y install nginx
-mkdir /etc/nginx/html
-touch /etc/nginx/html/index.html
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
-echo "Hello World!" > /etc/nginx/html/index.html
-touch /etc/nginx/html/404.html
-echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
 
-printf %s "server{
-    listen 80;
-    listen [::]:80 default_server;
-    add_header X-Served-By $HOSTNAME;
-    root /etc/nginx/html;
-    index index.html index.htm;
-    location /redirect_me{
-    	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
-    }
-    error_page 404 /404.html;
-    location /404 {
-    root /etc/nginx/html;
-    internal;
-    }
-}" > /etc/nginx/sites-available/default
 
-service nginx restart
+echo -e "Updating and checks...\n"
+
+function install() {
+	command -v "$1" &> /dev/null
+	
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "       Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "       ${1} already installed.\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
+
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+	"server {
+	listen 80 default_server;
+	listen [::]:80 default_server;
+	root /var/www/html;
+	index index.html index.htm index.nginx-debian.html
+	server_name_;
+	add_header X-Served-By \$hostname;
+	location / {
+	     try_files \$uri \$uri/ =404;
+        }
+	if (\$request_filename ~ redirect_me){
+	      rewrite ^ https://th3-gr00t.tk/ permanent;
+        }
+	error_page 404 /error_404.html;
+	location = /error_404.html {
+	internal;
+	}
+}"
+
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
